### ISSUE TITLE
Do you think it's safe to actually use?

### ISSUE THREAD

**Issue by MostHated** [keijiro/UnitySpanTest#1]
Hey there,
    I know *about* span, but not much more than knowing it exists primarily because it was not supported in Unity, so I never bothered to look into it more. From what I remember, it could be incredibly useful in the context of game development, though. 

The question is whether it would work in Jobs, and more importantly, do you think it would be safe to actually do so? I figured that it was not included/supported for some sort of reason, but I don't know if that reason had anything to do with unpredictable results, incompatibility with the Burst compiler, or anything along those lines. 

I realize that you may not know the answer, but since it is indeed working, do you think it is safe to try and make use of it, or is it more of a "hey, neat, it works" kind of thing and leave it at that?

Thanks,
-MH

**Comment by keijiro** [comment]
> because it was not supported in Unity, so I never bothered to look into it more.

`System.Span` has been available through [NuGet](https://github.com/xoofx/UnityNuGet). I used it in several Unity projects (e.g. KlakNDI and LASP).

> The question is whether it would work in Jobs, and more importantly, do you think it would be safe to actually do so?

No. It's not useful for Jobs.

> do you think it is safe to try and make use of it

It's quite useful and safe. I have used it in several Unity projects.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by MostHated** [comment]
My apologies, I simply meant that they didn't include it as a language feature within Unity releases, or so I thought. 

I appreciate the reply and information. I might have to look more into it after doing a few quick searches. :+1: Thanks.
